### ISSUE TITLE
Type mismatch on Raspberry Pi

### ISSUE THREAD

**Issue by Eiyeron** [deltaphc/raylib-rs#10]
Hello, I'm searching for a simple abstraction to make stuff on a Raspberry Pi and enjoy the hardware acceleration. And while raylib-rs seems to work on a computer, it fails to compile on a Raspberry Pi due to type mismatch.

```
    --> /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/raylib-0.9.1/src/lib.rs:2673:40
     |
2673 |             Shader(ffi::LoadShaderCode(c_vs_code.as_ptr() as *mut i8, c_fs_code.as_ptr() as *mut i8))
     |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected u8, found i8
     |
     = note: expected type `*mut u8`
                found type `*mut i8`
```

After browsing a bit the code, it seems that raylib-sys uses `::std::os::raw::c_char,` as type for shader code types and it seems that they indeed mismatches. CPP Reference even [mentions][^1] that default char type on ARM is an unsigned

I haven't got to understand what to do to avoid that except than hardcoding another type for the shader code, but at least I wanted to share you this issue.

Have a nice day and good luck with that wrapper! o/

[^1]:https://en.cppreference.com/w/cpp/language/types#Character_types

Update : looks like `.into_raw()` instead of `as_ptr() as ...` matches a bit better the intention : it consumes the `CString`, returns a mutable pointer to `c_char`, which is what `LoadShaderCode` requires independantly from the platform.

Inspired from what  `into_raw()`'s examples do to avoid leaking, I tried by replacing this snippet by something like this:
```rust
//...
        unsafe {
            let vs_code = c_vs_code.into_raw();
            let fs_code = c_fs_code.into_raw();
            let res = Shader(ffi::LoadShaderCode(vs_code, fs_code));
            let _ = CString::from_raw(vs_code);
            let _ = CString::from_raw(fs_code);
            res
        }
//...
```
It should make the function work on any platform. I'll try this this evening (GMT+1) to confirm if it works.

Edit : it works, do you need a PR?

**Comment by Vrixyz** [comment]
That MR getting merged would simplify getting headless support from this MR: https://github.com/deltaphc/raylib-rs/issues/52

**Comment by Dacode45** [comment]
So use into_raw() for everything. Got it.
