### ISSUE TITLE
Wayland?

### ISSUE THREAD

**Issue by yujiri8** [deltaphc/raylib-rs#119]
Running the hello world example for me is producing on wayland native is producing this error:
```
INFO: Initializing raylib 3.7
WARNING: GLFW: Error: 65544 Description: X11: The DISPLAY environment variable is missing
WARNING: GLFW: Failed to initialize GLFW
thread 'main' panicked at 'Attempting to create window failed!', /home/yujiri/.cargo/registry/src/github.com-1ecc6299db9ec823/raylib-3.7.0/src/core/mod.rs:208:13
```

I heard from the Nim bindings that Raylib is supposed to support Wayland, so does anyone know what I'd need to do to get that to work here? I tried installing packages for raylib and glfw-wayland just incase but that didn't have any effect.

OS: Artix Linux

**Comment by yujiri8** [comment]
Update: the upstream Raylib examples do not work out of the box for me either, so this is not an issue with raylib-rs. My apologies.

**Comment by yujiri8** [comment]
Update! I traced the issue with raylib upstream through glfw to me not having wayland-protocols installed. After installing that and rebuilding, raylib works natively on wayland for me, raylib-rs still does not.

**Comment by the-gremlin** [comment]
wouldn't this issue be resolved with the merging of #127 ?

**Comment by yujiri8** [comment]
Ah! Sorry, I didn't get a notification on this. Using the master version, I got a project using this crate to build but it segfaults on start, just after saying `INFO: Initializing raylib 3.7`.

**Comment by yujiri8** [comment]
I wonder if this could have to do with libc issues. I've switched to a musl distribution since

**Comment by yujiri8** [comment]
Indeed, it seems to work back on my Artix installation. RIP

**Comment by yujiri8** [comment]
I checked out upstream raylib 3.7 and could run the examples on my system without segfault

**Comment by yujiri8** [comment]
Update: by editing the downloaded C source in ~/.cargo/git/checkouts, I deducated that the problem is some sort of failure to load glfw, as the segfault occurs at the first call to glfw.

I don't know why. I've got glfw-wayland-dev installed, and the compiled binary for my project when examined with ldd shows:
```
	/lib/ld-musl-x86_64.so.1 (0x7f3ed4a31000)
	libglfw.so.3 => /usr/lib/libglfw.so.3 (0x7f3ed47cf000)
	libwayland-client.so.0 => /usr/lib/libwayland-client.so.0 (0x7f3ed47be000)
	libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f3ed4a31000)
	libffi.so.8 => /usr/lib/libffi.so.8 (0x7f3ed47b1000)
```
(interestingly, for some reason if built in x mode, ldd shows only ld-musl-x86_64)

**Comment by yujiri8** [comment]
Whoa, [this workaround](https://github.com/rust-lang/rust/issues/82193#issuecomment-1214341301) solved it for me!
