### ISSUE TITLE
Why raylib-sys ain't dynamically linked?

### ISSUE THREAD

**Issue by tahmidsadik112** [deltaphc/raylib-rs#16]
In the official wiki for Raylib, the recommended build type is shared dynamic libraries. Why doesn't raylib-sys work with dynamic libraries.

**Comment by Dacode45** [comment]
Dynamic linking wasn't working for all platforms in the past. With 0.11 static linking is the new norm.

**Comment by Dacode45** [comment]
Optional dynamic linking should be a goal for 0.12

**Comment by Dacode45** [comment]
Added a "nobuild" feature so you can do your own linking
