### ISSUE TITLE
Option to completely disable exit key

### ISSUE THREAD

**Issue by AregevDev** [deltaphc/raylib-rs#20]
Maybe changing `set_exit_key` to accept `Option<KeyboardKey>`, if it is `None`, set the exit key to zero.
You can match the parameter in the function

**Comment by AregevDev** [comment]
```rust
pub fn set_exit_key(&mut self, key: Option<crate::consts::KeyboardKey>) {
        unsafe {
            match key {
                Some(k) => ffi::SetExitKey((k as u32) as i32),
                None => ffi::SetExitKey(0),
            }
        }
    }
```
Something like that

**Comment by Dacode45** [comment]
Wouldn't this overcomplicate the api. I feel like people should not be calling this method unless they want to explicitly set the exit key. I also don't want people to have to look up what key None defaults too or think passing None makes it impossible to exit.

**Comment by AregevDev** [comment]
And if I want to disable exit key completely?

**Comment by Dacode45** [comment]
I see your point. Since people are probably only going to call this once I think you're right. I'll put it in 0.11
