### ISSUE TITLE
Raylib builds in my OUT_DIR/lib64 instead of OUT_DIR/lib

### ISSUE THREAD

**Issue by DevJac** [deltaphc/raylib-rs#26]
[I had to hack the build script](https://github.com/DevJac/raylib-rs/commit/3183373300356f2205695cc66447f6a54d17e0b6) to make `raylib-sys` build on Fedora 30.

I'm not a `cmake` expert, I don't know why raylib was build in `lib64` instead of `lib`. Any ideas?

I'm willing to contribute a fix.

A naive solution would be to check whether a `lib` or a `lib64` directory was created by `cmake` and use the appropriate directly, but there might be a better solution if we can determine exactly which directory we should expect to be used. In other words, it could be better to understand what `cmake` is going to do in advance, rather than just reacting "with surprise" to whatever it does after the fact

**Comment by Dacode45** [comment]
I'll be honest. I have a meager understanding of how CMake works, and no clue on how it works across platforms. If you can submit a PR that checks the target to distinguish between lib64 and lib, I'd merge it.
