### ISSUE TITLE
Set an environment variable to a local raylib download

### ISSUE THREAD

**Issue by DevJac** [deltaphc/raylib-rs#27]
I would like to be able to set an environment variable to point to a local raylib download I have somewhere (or anywhere) on my system. The build script would then use this rather than downloading raylib.

I would probably copy the raylib download into `OUT_DIR`, so that `cmake` can run inside `OUT_DIR`. This would remove any uncertainty around `cargo clean` and such. The environment variable could point to a raylib tar archive or a regular raylib directory.

I am willing to implement this, but wanted to "get approval" first.

Would this be a good feature? Any opinion on what the environment variable should be called?

**Comment by Dacode45** [comment]
It's a good idea to let people have their own copy of raylib, but if they already downloaded raylib they might as well build it and put it /usr/local/lib or somewhere for raylib-rs to pick up. Back in the day, raylib-sys did just this. 

https://github.com/deltaphc/raylib-rs/blob/484cd594379dda8780f245d96f00054e8895b629/raylib-sys/build.rs 

Of course, this could be customized even further. 

https://github.com/dtcristo/raylib-rust/blob/master/raylib-sys/build.rs

I was planning on bringing this back under a feature flag for 0.12. If you want to submit a PR I'd merge it.

**Comment by Dacode45** [comment]
Added a "nobuild" feature so you can do your own linking
