### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by Pebaz** [deltaphc/raylib-rs#30]
The documentation for versions [0.11.1](https://docs.rs/crate/raylib/0.11.1) and [0.11.2](https://docs.rs/crate/raylib/0.11.2) are out of date.

It may be more correct to say they don't exist.

**Comment by Dacode45** [comment]
docs.rs changed how they build crates. They now build with a special container that doesn't have all the dependencies raylib requires to be built. Mainly curl. Nothing changed in library usage since 0.11.0 so you can use those docs. Or you can build the docs manually with cargo doc.

**Comment by Pebaz** [comment]
Good to know, I'll build them locally. Thank you

**Comment by Dacode45** [comment]
Fixed 
https://docs.rs/raylib/1.0.0/raylib/
