### ISSUE TITLE
Issue following current README.md

### ISSUE THREAD

**Issue by danbugs** [deltaphc/raylib-rs#31]
Long story short, following the **Installation** section of README.md, gave me an error.

Recreating issue:
1. `cargo new raylib_test`
1. Add dependency as per instruction. 
1. Copy and paste README.md sample code in main.rs
1. `cargo run`

Result:
![LHK3_8uk](https://user-images.githubusercontent.com/39843321/69483595-1c7bd600-0dde-11ea-86a9-00deba6c4a02.jpg)

I talked to Ray and he asked me to post this here. Thanks in advance! (:

**Comment by Dacode45** [comment]
raylib-rs requires cmake. You'll have to install it to build raylib.
