### ISSUE TITLE
Upgrading to raylib 2.5

### ISSUE THREAD

**Issue by Nachasic** [deltaphc/raylib-rs#36]
Second version of raylib has some tasty functionality I'd like to be able to use in my rust projects, look at the [changelog](https://github.com/raysan5/raylib/blob/master/CHANGELOG)

So I've been flirting with the idea of upgrading bindings to work with latest raylib. However, since I only have surface-level familiarity with it, it's hard for me to make estimations.

How feasible would that be? I don't have much experience with FFI (have done it before once), but I'd be happy to help.

**Comment by Dacode45** [comment]
The current bindings are for raylib 2.5. 
Every function on the cheatsheet is in raylib-rs somewhere.
https://www.raylib.com/cheatsheet/cheatsheet.html

**Comment by Nachasic** [comment]
@Dacode45 oh, okay. I was mislead by readme - might wanna update it. Thanks)
