### ISSUE TITLE
High CPU usage running the Hello World example

### ISSUE THREAD

**Issue by christophemarois** [deltaphc/raylib-rs#40]
On latest macOS, installing went like a charm. However, running the current README's hello world example, even built in release mode using `cargo build --release`, I get a CPU usage of over 75%.

Am I missing something? I'm quite new to the Rust ecosystem.

**Edit** It looks like a mistake on my behalf that is out of scope for this library (which is awesome btw). I just needed to cap the FPS with:

```rust
rl.set_target_fps(60u32);
```

Might be worth putting in your Hello World example. Thanks again!

**Comment by Dacode45** [comment]
Good find. You might also fix it by setting vsync as explained in this issue
https://github.com/raysan5/raylib/issues/217

**Comment by christophemarois** [comment]
@Dacode45 That's great. Using vsync, I get 55-60fps in average, and my CPU is super quiet. Thank you!
