### ISSUE TITLE
Updating raylib to 2.6?

### ISSUE THREAD

**Issue by ecton** [deltaphc/raylib-rs#47]
I have a local copy that I've updated to point to 2.6.0, and it works fine for me, but I don't pretend to know how to test whether it's safe to send up a PR for it. For me, I need 2.6 because my primary machine is a Mac and Camera2D is broken in 2.5 on high dpi displays but is fixed by changes in 2.6.

I'm happy to do some more legwork to help update. If the only step is the one above, then I'm happy to send a PR up, I just am suspecting there's a lot more to do. For now, I'm not blocked, so this isn't urgent in any way.

Thanks for the great bindings!

**Comment by Dacode45** [comment]
3.0 is right around the corner. I was going to skip 2.6 to update bindings then. Would you mind waiting a few days?

**Comment by ecton** [comment]
Absolutely, no rush on my behalf. Thanks!

**Comment by eliukblau** [comment]
It's released! 😃👏
https://raysan5.itch.io/raylib/devlog/134369/raylib-30-released

**Comment by ecton** [comment]
Thank you!
