### ISSUE TITLE
Is it possible to configure the open gl version ?

### ISSUE THREAD

**Issue by phtrivier** [deltaphc/raylib-rs#54]
When running the raylib-rs examples on an old machine, I got an error because GLFW could not initialize the window. 

It seems like it was related to the OpenGL version.
I managed to recompile the `raylib` examples themselves following https://github.com/raysan5/raylib/wiki/FAQ#can-i-run-raylib-in-my-old-pc

However, would there be a way to configure an application using `raylib-rs` so that is compiles / recompiles / links against a version of raylib with the proper configuration ? 

(I don't know if it is something that can be done in cargo, for example...)

**Comment by jestarray** [comment]
what opengl version do you need? can you post the error?

**Comment by Dacode45** [comment]
You can compile raylib-rs with the nobuild feature and then manually link the shared library using your systems dynamic linking mechanism.

**Comment by phtrivier** [comment]
The error (for rust code just trying to open a window) is  
```
    Finished dev [unoptimized + debuginfo] target(s) in 14.32s
     Running `/home/phtrivier/prj/wirth/target/debug/gui-raylib`
INFO: Initializing raylib 2.5
WARNING: [GLFW3 Error] Code: 65543 Decription: GLX: Failed to create context: GLXBadFBConfig
WARNING: GLFW Failed to initialize Window
Segmentation fault (core dumped)
```

My glx versions is pretty old: 

```
phtrivier@oscar:~/prj/wirth/gui-raylib$ glxinfo | grep version
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 0.0
    Max compat profile version: 2.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 2.0
OpenGL version string: 2.1 Mesa 19.2.8
OpenGL shading language version string: 1.20
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 19.2.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
```

In order to compile the core `raylib` examples, I had to pass configuration to `cmake`: 

```
cd raylib
cmake -DGRAPHICS=GRAPHICS_API_OPENGL_21
cd examples
make
```

So I'm wondering if there is something in `raylib-rs` that requires a `raylib` version compiled with OpenGL3.3 ? Or if it's possible to use multiple versions (possibly at runtime ?)

Or is it required to compile multiple versions of an application, for each opengl supported version ?

**Comment by jestarray** [comment]
As far as I know, there isn't anything in the rust bindings that requires opengl 3.3 as its just wrapping around raylib functions. You need to configure https://github.com/deltaphc/raylib-rs/blob/master/raylib-sys/build.rs#L185 , the `build.rs` file to point to your custom version. The easiest way to get this working is to upload your modifications to github and release it, then just have the url point to it.

**Comment by Dacode45** [comment]
I'm going to close this. Use the nobuild feature.

https://github.com/deltaphc/raylib-rs/wiki/Using-%5B%22nobuild%22%5D-feature.

**Comment by j-cr** [comment]
The link is broken for me. Maybe rename the wiki page to not include the fancy chars?

**Comment by Dacode45** [comment]
https://github.com/deltaphc/raylib-rs/wiki/Using-nobuild-feature
