### ISSUE TITLE
Explain nobuild feature on README.md

### ISSUE THREAD

**Issue by codemessiah** [deltaphc/raylib-rs#56]
Hello, I was going to make a PR for a download and build ["bundled" feature like SDL2 has](https://github.com/Rust-SDL2/rust-sdl2#bundled-feature), but found you already have one in place! Excellent. But, even though I read through code and raylib-sys Cargo.toml, I see [I need to somehow disable nobuild feature](https://github.com/deltaphc/raylib-rs/blob/master/raylib-sys/build.rs#L28), but I have no idea how to do that.

It would be fantastic if it were explained in the build section of the raylib-rs readme.md file!

**Comment by Dacode45** [comment]
Makes sense

**Comment by Dacode45** [comment]
Made a wiki
https://github.com/deltaphc/raylib-rs/wiki/Using-%5B%22nobuild%22%5D-feature.
