### ISSUE TITLE
load_model_from_mesh() doesn't work from generated meshes. 

### ISSUE THREAD

**Issue by rosenjcb** [deltaphc/raylib-rs#57]
If you use `load_model_from_mesh()`, it simply won't work. The reason? Raylib's documentation states that `LoadModelFromMesh()` generates a model with a default material. However, the method in question will actually return an Error if the generated model doesn't have `bones` or a `bindPose`.

```
    pub fn load_model_from_mesh(&mut self, _: &RaylibThread, mesh: &Mesh) -> Result<Model, String> {
        let m = unsafe { ffi::LoadModelFromMesh(mesh.0) };

        if m.meshes.is_null() || m.materials.is_null() || m.bones.is_null() || m.bindPose.is_null()
        {
            return Err("Could not load model from mesh".to_owned());
        }

        Ok(Model(m))
    }
}
```

The solution? `bones` and `bindPose` could have default values provided for them. 

As of now, this function is arguably completely broken because there is no instance where you may create a mesh with a provided `bones` and `bindPose` using the safe Rust bindings.

**Comment by bhgsbatista** [comment]
Is this fixed?

**Comment by rosenjcb** [comment]
@bhgsbatista Technically "yes", but I think the resulting mesh is easy to break. @Dacode45 recommends in  `...using raylib-sys to call LoadModelFromMesh directly.`

**Comment by Dacode45** [comment]
It's in https://github.com/deltaphc/raylib-rs/pull/63
