### ISSUE TITLE
Compilation on Alpine Linux (musl libc)

### ISSUE THREAD

**Issue by refacto** [deltaphc/raylib-rs#59]
To compile on Alpine Linux, I had to set the following RUSTFLAGS:

`-Ctarget-feature=-crt-static`

Would a PR documenting that be appreciated?

**Comment by bhgsbatista** [comment]
This is something that should likely go on the Wiki, in a section dedicated to various platform details.

**Comment by Dacode45** [comment]
Added one
https://github.com/deltaphc/raylib-rs/wiki/Working-on-GNU-Linux
