### ISSUE TITLE
Cross compiling to windows from linux

### ISSUE THREAD

**Issue by Kirottu** [deltaphc/raylib-rs#66]
I have added the target x86_64-pc-windows-gnu, and installed the toolchains for it and the mingw compiler. But when trying to build the project linking with x86_64-w64-mingw32-gcc failed, as it was trying to link the X11 library for some reason.

**Comment by Ewpratten** [comment]
Same for me with the `cross` tool

**Comment by Ewpratten** [comment]
The cause is pretty clearly [these lines](https://github.com/deltaphc/raylib-rs/blob/ec4245e7a154b653f98ac2150c7a400584159d43/raylib-sys/build.rs#L252-L254) I'll look in to fixing this
