### ISSUE TITLE
TextSubtext not implemented?

### ISSUE THREAD

**Issue by varomix** [deltaphc/raylib-rs#71]
Hi
I was porting some examples from C to basically learn more Rust and Raylib at the same time
everything has been working great until I found TextSubtext.

I found that it is part of the ffi implementation, so I tried calling it for there,
didn't have much luck with that

a few questions
is this something that is pending to be implemented?
is there a way I can help?

this is the code I'm trying, could be totally wrong
```rust
let title = CString::new("raylib").expect("Cstring failed").as_ptr();
                unsafe {
                    d.draw_text(std::str::from_utf8(*(ffi::TextSubtext("title\0".as_ptr() as *const i8 , 0, letters_count))).unwrap(), SCREEN_WIDTH / 2 - 44, SCREEN_HEIGHT / 2 + 48, 50, Color::fade(&Color::BLACK, alpha));
                }
```

this is the example where that is used
https://www.raylib.com/examples/web/shapes/loader.html?name=shapes_logo_raylib_anim

Thank you

**Comment by Dacode45** [comment]
The string manipulation functions that come with rust are much better (and safer) than the raylib ones. We will not be porting them over.

**Comment by varomix** [comment]
Sounds good, I used Rust string substrings and that works
thanks
