### ISSUE TITLE
Implement DerefMut for RaylibDrawHandle

### ISSUE THREAD

**Issue by creikey** [deltaphc/raylib-rs#74]
I'm trying to use the raylib draw handle to copy to the clipboard:

`d.set_clipboard_text("test")`

This is done because I am passing the raylib draw handle into a function, and I can't mutably borrow the raylib handle twice to drop down to it. However, because DerefMut is not implemented for RaylibDrawHandle, I don't have mutable access to the raylib API.

Would something like this work?
```rust
impl<'a> std::ops::DerefMut for RaylibDrawHandle<'a> {
    type Target = RaylibHandle;

    fn deref(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
```

**Comment by Dacode45** [comment]
RaylibDrawHandle explicitly doesn't implement DerefMut because it is a very bad idea to change raylib state while drawing. If you want to change state (call set_clipboard_text), do it before calling begin_drawing.

**Comment by creikey** [comment]
> RaylibDrawHandle explicitly doesn't implement DerefMut because it is a very bad idea to change raylib state while drawing. If you want to change state (call set_clipboard_text), do it before calling begin_drawing.

Thanks for the advice!
