### ISSUE TITLE
Raylib 3.7

### ISSUE THREAD

**Issue by Ewpratten** [deltaphc/raylib-rs#80]
This project should be updated to the latest version of raylib. To quote @raysan5 in discord:

 > Note that *official* `raylib 3.7` release is expected in the following days but it's already on github main branch.

Once I'm done with Ludum Dare this weekend, I can help bring this repo up to date if needed.

**Comment by Ewpratten** [comment]
3.7 has been officially released: https://github.com/raysan5/raylib/releases/tag/3.7.0

**Comment by raysan5** [comment]
@Ewpratten Wow! That was fast! I'm still preparing the installers and the announcement! :D

**Comment by Ewpratten** [comment]
I looked at my GitHub homepage at the right time I guess @raysan5

**Comment by Dacode45** [comment]
With that much enthusiasm, I got to get it out

**Comment by Ewpratten** [comment]
I'm building the latest version in my fork right now. Currently working out what appears to be some bindgen issues.
