### ISSUE TITLE
raylib-sys build failed

### ISSUE THREAD

**Issue by LoooongName** [deltaphc/raylib-rs#89]
Compiling cc v1.0.68
   Compiling fs_extra v1.2.0
   Compiling libc v0.2.97
   Compiling lazy_static v1.4.0
   Compiling cmake v0.1.45
   Compiling raylib-sys v3.5.0
error: failed to run custom build command for 'raylib-sys v3.5.0'

Caused by:
  process didn't exit successfully: '`/home/username/VsCodeProjects/Rust/learn/target/debug/build/raylib-sys-30f02b9f8cb9c24a/build-script-build' (exit status: 101)
  --- stdout
  running: "cmake" "/home/username/VsCodeProjects/Rust/learn/target/debug/build/raylib-sys-f29fe605cf807025/out/raylib" "-DBUILD_EXAMPLES=OFF" "-DBUILD_GAMES=OFF" "-DCMAKE_BUILD_TYPE=Release" "-DSUPPORT_BUSY_WAIT_LOOP=OFF" "-DSTATIC=TRUE" "-DPLATFORM=Desktop" "-DCMAKE_INSTALL_PREFIX=/home/username/VsCodeProjects/Rust/learn/target/debug/build/raylib-sys-f29fe605cf807025/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc"
  -- The C compiler identification is GNU 10.3.0
  -- The CXX compiler identification is GNU 10.3.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Performing Test COMPILER_HAS_THOSE_TOGGLES
  -- Performing Test COMPILER_HAS_THOSE_TOGGLES - Success
  -- Testing if -Werror=pointer-arith can be used -- compiles
  -- Testing if -Werror=implicit-function-declaration can be used -- compiles
  -- Testing if -fno-strict-aliasing can be used -- compiles
  -- Using raylib's GLFW
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - found
  -- Found Threads: TRUE  
  -- Using X11 for window creation
  -- Configuring incomplete, errors occurred!
  See also "/home/username/VsCodeProjects/Rust/learn/target/debug/build/raylib-sys-f29fe605cf807025/out/build/CMakeFiles/CMakeOutput.log".
  See also "/home/username/VsCodeProjects/Rust/learn/target/debug/build/raylib-sys-f29fe605cf807025/out/build/CMakeFiles/CMakeError.log".

  --- stderr
  CMake Warning (dev) in CMakeLists.txt:
    No project() command is present.  The top-level CMakeLists.txt file must
    contain a literal, direct call to the project() command.  Add a line of
    code such as

      project(ProjectName)

    near the top of the file, but after cmake_minimum_required().

    CMake is pretending there is a "project(Project)" command on the first
    line.
  This warning is for project developers.  Use -Wno-dev to suppress it.

  CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
    Could NOT find X11 (missing: X11_X11_INCLUDE_PATH X11_X11_LIB)
  Call Stack (most recent call first):
    /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
    /usr/share/cmake-3.18/Modules/FindX11.cmake:414 (find_package_handle_standard_args)
    src/external/glfw/CMakeLists.txt:204 (find_package)

  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 1

  build script failed, must exit now', /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.45/src/lib.rs:894:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by verticalegg** [comment]
This occurs when the raylib submodule located in raylib-sys isn't initialized. Try running 
```
git submodule init
git submodule update
```
which should pull raylib.
